= NMEA2000_stm32f1 library for Arduino =


Inherited object for use NMEA2000 library for the stm32f103 "bluepill" Boards with
its internal CAN controller See also NMEA2000 library.

To use this library, you will also need NMEA2000 and official STM32 port to Arduino

https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

Tested on a stm32f103C8 and STM32 versions 2017.11.24 and 2018.1.18 

== License ==

Copyright (c) 2017-2018 Jaume Clarens jiauka_at_gmail_dot_com

Author: Jaume Clarens

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-
  1301  USA
